BRAND_NAME = "GitBlocks"
BRAND_SLUG = "gitblocks"
BRAND_DESCRIPTION = "Git-backed datablock version control for Blender"

ADDON_NAME = BRAND_NAME
ADDON_SLUG = BRAND_SLUG
ADDON_DESCRIPTION = BRAND_DESCRIPTION

UI_BRAND_NAME = BRAND_NAME
UI_CATEGORY = BRAND_NAME
UI_LOG_PREFIX = BRAND_NAME

MAIN_PANEL_ID = "GITBLOCKS_PT_main"
CHANGES_PANEL_ID = "GITBLOCKS_PT_changes"
HISTORY_PANEL_ID = "GITBLOCKS_PT_history"
BRANCHES_PANEL_ID = "GITBLOCKS_PT_branches"
CONFLICTS_PANEL_ID = "GITBLOCKS_PT_conflicts"

UI_REFRESH_PANEL_IDS = (CHANGES_PANEL_ID, HISTORY_PANEL_ID, BRANCHES_PANEL_ID)
