BRAND_NAME = "GitBlocks"
BRAND_SLUG = "gitblocks"
BRAND_DESCRIPTION = "Git-backed datablock version control for GitBlocks"

LEGACY_BRAND_NAME = "Cozy Studio"
LEGACY_BRAND_SLUG = "cozystudio"

# Compatibility aliases kept for older saves, logs, and registration identifiers.
PUBLIC_BRAND_NAME = BRAND_NAME
PUBLIC_BRAND_SLUG = BRAND_SLUG
COMPAT_BRAND_NAME = LEGACY_BRAND_NAME
COMPAT_BRAND_SLUG = LEGACY_BRAND_SLUG

ADDON_NAME = BRAND_NAME
ADDON_SLUG = BRAND_SLUG
ADDON_DESCRIPTION = BRAND_DESCRIPTION

LEGACY_ADDON_NAME = LEGACY_BRAND_NAME
LEGACY_ADDON_SLUG = LEGACY_BRAND_SLUG

UI_BRAND_NAME = BRAND_NAME
UI_CATEGORY = BRAND_NAME
UI_LOG_PREFIX = BRAND_NAME

# Compatibility panel ids remain centralized here so backend redraw hooks can
# swap namespaces without touching call sites.
LEGACY_PANEL_PREFIX = f"{LEGACY_BRAND_SLUG.upper()}_PT"
MAIN_PANEL_ID = f"{LEGACY_PANEL_PREFIX}_main"
CHANGES_PANEL_ID = f"{LEGACY_PANEL_PREFIX}_changes"
HISTORY_PANEL_ID = f"{LEGACY_PANEL_PREFIX}_history"
BRANCHES_PANEL_ID = f"{LEGACY_PANEL_PREFIX}_branches"
CONFLICTS_PANEL_ID = f"{LEGACY_PANEL_PREFIX}_conflicts"

UI_REFRESH_PANEL_IDS = (CHANGES_PANEL_ID, HISTORY_PANEL_ID, BRANCHES_PANEL_ID)
