BRAND_NAME = "GitBlocks"
BRAND_SLUG = "gitblocks"
BRAND_DESCRIPTION = "Git-backed datablock version control for GitBlocks"

ADDON_NAME = BRAND_NAME
ADDON_SLUG = BRAND_SLUG
ADDON_DESCRIPTION = BRAND_DESCRIPTION

UI_BRAND_NAME = BRAND_NAME
UI_CATEGORY = BRAND_NAME
UI_LOG_PREFIX = BRAND_NAME
